name: bb-touch-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - ta-lib
  - aiohttp
  - redis-py
  # uvloop makes asyncio 2-4x faster. 
  # NOTE: If you are on WINDOWS, delete the line below (uvloop is Linux/Mac only).
  - uvloop 
  - pip
